In [1]:
import numpy as np

In [2]:
import numpy as np
x = np.random.randint(low=0, high=20, size=15)
print(x)


[ 1  5 16 10 15  9 12 17 15 17  3  3 14  5  1]


In [3]:
x=x.reshape(3,5)
x

array([[ 1,  5, 16, 10, 15],
       [ 9, 12, 17, 15, 17],
       [ 3,  3, 14,  5,  1]])

In [4]:
x.shape

(3, 5)

In [8]:
x[x==x.max()]=0
x

array([[ 1,  5,  0, 10,  0],
       [ 9, 12,  0,  0,  0],
       [ 3,  3,  0,  5,  1]])